In [8]:
import numpy as np

In [14]:
def compute_vector_length(vector):
    return np.sum(vector**2)**0.5

vector = np.array([1,2,3,4])
compute_vector_length(vector)

5.477225575051661

In [16]:
def compute_dot_product(vector1, vector2):
    result = np.sum(vector1 * vector2)
    return result

vector1 = np.array([1,2,3,4])
vector2 = np.array([2,3,4,5])
compute_dot_product(vector1, vector2)

40

In [18]:
def matrix_multi_vector(matrix , vector):
    result = matrix.dot(vector)
    return result

matrix = np.array([[1,2,3], [2,3,4], [3,4,5]])
vector = np.array([1,1,1])
matrix_multi_vector(matrix , vector)

array([ 6,  9, 12])

In [21]:
def matrix_multi_matrix(matrix1, matrix2):
    len_of_vector = matrix1.dot(matrix2)
    return len_of_vector

matrix1 = np.array([[1,2,3], [2,3,4], [3,4,5]])
matrix2 = np.array([[4,-1], [1,2], [-5,-2]])
matrix_multi_matrix(matrix1, matrix2)


array([[-9, -3],
       [-9, -4],
       [-9, -5]])

In [13]:
def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    return result

matrix = np.array([[-2,6], [8,-4]])
inverse_matrix(matrix)

array([[0.1 , 0.15],
       [0.2 , 0.05]])